// Curated finance icons with friendly labels and searchable keywords.
export const EXPENSE_CATEGORY_ICON_CATALOGUE = [
    { name: "tag-outline", label: "General", keywords: "misc miscellaneous category label other" },
    { name: "silverware-fork-knife", label: "Dining", keywords: "food restaurant eating meals dinner lunch" },
    { name: "food", label: "Food", keywords: "meals eating takeaway snacks" },
    { name: "food-apple", label: "Fruit", keywords: "food produce groceries healthy" },
    { name: "food-fork-drink", label: "Restaurant", keywords: "food dining meals drinks" },
    { name: "coffee", label: "Coffee", keywords: "cafe drinks breakfast" },
    { name: "coffee-outline", label: "Cafe", keywords: "coffee tea drinks" },
    { name: "cup-water", label: "Drinks", keywords: "food beverages water juice" },
    { name: "cake-variant", label: "Cake", keywords: "food dessert bakery birthday celebration" },
    { name: "ice-cream", label: "Ice cream", keywords: "food dessert snacks" },
    { name: "pizza", label: "Pizza", keywords: "food restaurant takeaway delivery" },
    { name: "hamburger", label: "Fast food", keywords: "food burger restaurant takeaway" },
    { name: "noodles", label: "Noodles", keywords: "food restaurant meals" },
    { name: "basket", label: "Groceries", keywords: "food supermarket produce shopping" },
    { name: "cart", label: "Shopping cart", keywords: "shopping groceries supermarket food" },
    { name: "car", label: "Car", keywords: "transport auto vehicle driving" },
    { name: "car-electric", label: "Electric car", keywords: "transport auto vehicle charging electricity" },
    { name: "car-wrench", label: "Car maintenance", keywords: "transport auto vehicle repair service" },
    { name: "gas-station", label: "Fuel", keywords: "car transport petrol diesel gasoline" },
    { name: "parking", label: "Parking", keywords: "car transport vehicle fees" },
    { name: "train", label: "Train", keywords: "transport rail metro mrt commute" },
    { name: "bus", label: "Bus", keywords: "transport public commute" },
    { name: "taxi", label: "Taxi", keywords: "transport car ride rideshare grab uber" },
    { name: "bicycle", label: "Bicycle", keywords: "transport cycling fitness sports" },
    { name: "motorbike", label: "Motorbike", keywords: "transport motorcycle scooter" },
    { name: "walk", label: "Walking", keywords: "transport fitness hiking" },
    { name: "airplane", label: "Flight", keywords: "plane travel transport air ticket" },
    { name: "airplane-takeoff", label: "Air travel", keywords: "plane flight airport holiday" },
    { name: "ferry", label: "Ferry", keywords: "boat cruise travel transport" },
    { name: "bag-suitcase", label: "Luggage", keywords: "travel holiday trip baggage" },
    { name: "map-marker", label: "Destination", keywords: "travel trip location outing" },
    { name: "beach", label: "Holiday", keywords: "travel vacation recreation" },
    { name: "bed", label: "Accommodation", keywords: "travel hotel home lodging rent" },
    { name: "bed-double", label: "Hotel", keywords: "travel accommodation lodging stay" },
    { name: "passport", label: "Passport", keywords: "travel visa documents fees" },
    { name: "shopping", label: "Shopping", keywords: "retail purchases bag store" },
    { name: "shopping-outline", label: "Shopping bag", keywords: "retail store purchases" },
    { name: "tshirt-crew", label: "Clothing", keywords: "shopping fashion clothes apparel" },
    { name: "hanger", label: "Wardrobe", keywords: "clothing shopping laundry dry cleaning" },
    { name: "shoe-sneaker", label: "Shoes", keywords: "clothing shopping fashion footwear sports" },
    { name: "watch", label: "Watch", keywords: "shopping accessories jewellery" },
    { name: "cellphone", label: "Electronics", keywords: "shopping phone mobile gadgets" },
    { name: "laptop", label: "Computer", keywords: "electronics shopping work technology" },
    { name: "headphones", label: "Headphones", keywords: "electronics music audio shopping" },
    { name: "monitor", label: "Monitor", keywords: "electronics computer work office" },
    { name: "gamepad-variant", label: "Gaming", keywords: "game entertainment console games hobby" },
    { name: "movie-open", label: "Movies", keywords: "film cinema entertainment subscription" },
    { name: "music", label: "Music", keywords: "entertainment concert streaming hobby subscription" },
    { name: "ticket", label: "Tickets", keywords: "events entertainment cinema concerts travel" },
    { name: "calendar-star", label: "Events", keywords: "celebration festival party birthday" },
    { name: "television", label: "Television", keywords: "entertainment streaming subscriptions media" },
    { name: "repeat", label: "Subscriptions", keywords: "recurring membership streaming bills" },
    { name: "receipt", label: "Bills", keywords: "utilities payment invoice taxes" },
    { name: "file-document-outline", label: "Documents", keywords: "bills administration paperwork fees" },
    { name: "lightbulb-outline", label: "Utilities", keywords: "home electricity bills lighting" },
    { name: "flash", label: "Electricity", keywords: "utilities power energy bills charging" },
    { name: "water", label: "Water", keywords: "utilities bills plumbing" },
    { name: "wifi", label: "Internet", keywords: "utilities broadband network bills" },
    { name: "router-wireless", label: "Broadband", keywords: "internet utilities wifi home network" },
    { name: "phone", label: "Phone", keywords: "mobile telephone utilities calls bills" },
    { name: "home", label: "Home", keywords: "housing rent mortgage household" },
    { name: "home-city", label: "Housing", keywords: "home property rent mortgage" },
    { name: "key", label: "Rent", keywords: "home housing property keys" },
    { name: "tools", label: "Tools", keywords: "home renovation repairs maintenance work" },
    { name: "hammer-wrench", label: "Renovation", keywords: "home repairs construction maintenance" },
    { name: "sofa", label: "Furniture", keywords: "home household furnishings shopping" },
    { name: "heart-pulse", label: "Health", keywords: "medical wellness doctor healthcare" },
    { name: "medical-bag", label: "Medical", keywords: "health clinic doctor healthcare" },
    { name: "pill", label: "Medicine", keywords: "health medical pharmacy prescriptions" },
    { name: "hospital-box", label: "Hospital", keywords: "health medical doctor treatment" },
    { name: "tooth-outline", label: "Dental", keywords: "health medical dentist teeth" },
    { name: "eye-outline", label: "Vision", keywords: "health medical glasses optician" },
    { name: "dumbbell", label: "Fitness", keywords: "health gym exercise sports membership" },
    { name: "run", label: "Running", keywords: "fitness sports exercise marathon" },
    { name: "soccer", label: "Football", keywords: "sports fitness recreation hobby" },
    { name: "basketball", label: "Basketball", keywords: "sports fitness recreation hobby" },
    { name: "swim", label: "Swimming", keywords: "sports fitness pool recreation" },
    { name: "school", label: "Education", keywords: "study tuition school university learning" },
    { name: "book-open-variant", label: "Learning", keywords: "education books study tuition" },
    { name: "book-outline", label: "Books", keywords: "education reading library hobby" },
    { name: "pencil", label: "Stationery", keywords: "education work office school supplies" },
    { name: "briefcase", label: "Work", keywords: "job office career salary employment" },
    { name: "office-building", label: "Office", keywords: "work job rent coworking" },
    { name: "printer", label: "Printing", keywords: "office work stationery supplies" },
    { name: "gift", label: "Gifts", keywords: "presents birthday celebration shopping" },
    { name: "paw", label: "Pets", keywords: "animals food vet veterinary care" },
    { name: "dog", label: "Dog", keywords: "pets animals vet veterinary" },
    { name: "cat", label: "Cat", keywords: "pets animals vet veterinary" },
    { name: "scissors-cutting", label: "Haircut", keywords: "beauty personal care grooming salon" },
    { name: "lipstick", label: "Beauty", keywords: "cosmetics makeup shopping personal care" },
    { name: "bottle-tonic-plus", label: "Personal care", keywords: "beauty skincare toiletries hygiene" },
    { name: "spa", label: "Wellness", keywords: "beauty health massage relaxation" },
    { name: "account-group", label: "Family", keywords: "children household parents dependents" },
    { name: "baby-carriage", label: "Children", keywords: "family baby childcare nursery" },
    { name: "baby-face-outline", label: "Baby", keywords: "children family nappies childcare" },
    { name: "piggy-bank", label: "Savings", keywords: "money banking emergency fund" },
    { name: "bank", label: "Banking", keywords: "money finance savings account fees" },
    { name: "credit-card-outline", label: "Cards", keywords: "money banking payment credit debit" },
    { name: "cash", label: "Cash", keywords: "money payment income salary" },
    { name: "cash-multiple", label: "Salary", keywords: "money income wages payment" },
    { name: "wallet", label: "Wallet", keywords: "money income salary banking payment" },
    { name: "currency-usd", label: "Money", keywords: "cash income currency finance" },
    { name: "chart-line", label: "Investment", keywords: "money finance stocks shares portfolio" },
    { name: "finance", label: "Finance", keywords: "money investment stocks banking" },
    { name: "shield-check", label: "Insurance", keywords: "money protection health car home premiums" },
    { name: "file-percent-outline", label: "Taxes", keywords: "money government duty finance fees" },
    { name: "hand-heart", label: "Charity", keywords: "money donation giving community" },
    { name: "palette", label: "Art", keywords: "hobbies hobby craft painting supplies" },
    { name: "camera", label: "Photography", keywords: "hobbies hobby electronics photos" },
    { name: "flower", label: "Gardening", keywords: "hobbies hobby plants home flowers" },
    { name: "puzzle", label: "Games", keywords: "game hobbies hobby puzzles entertainment" },
    { name: "dots-horizontal-circle-outline", label: "Miscellaneous", keywords: "general misc other category" },
] as const;

export type ExpenseCategoryIcon = (typeof EXPENSE_CATEGORY_ICON_CATALOGUE)[number]["name"];
export const EXPENSE_CATEGORY_ICONS = EXPENSE_CATEGORY_ICON_CATALOGUE.map((entry) => entry.name);
const ICON_KEYS = new Set<string>(EXPENSE_CATEGORY_ICONS);

export function searchExpenseCategoryIcons(query: string) {
    const terms = query.trim().toLowerCase().split(/\s+/).filter(Boolean);
    const entries = EXPENSE_CATEGORY_ICON_CATALOGUE.map((entry) => ({
        entry,
        words: `${entry.name} ${entry.label} ${entry.keywords}`.toLowerCase().split(/[^a-z0-9]+/),
    }));
    // Prefer whole keywords when available ("car" must not match "care" or "card").
    // Prefix matching still supports incremental typing such as "cof" for coffee.
    const exactTerms = terms.map((term) => entries.some(({ words }) => words.includes(term)));
    return entries.filter(({ words }) => terms.every((term, index) =>
        words.some((word) => exactTerms[index] ? word === term : word.startsWith(term)),
    )).map(({ entry }) => entry);
}

const DEFAULT_ICONS: Record<string, ExpenseCategoryIcon> = {
    food: "silverware-fork-knife", dining: "silverware-fork-knife",
    transport: "car", transportation: "car", shopping: "shopping",
    groceries: "basket", bills: "receipt", utilities: "lightbulb-outline",
    entertainment: "movie-open", travel: "airplane", health: "heart-pulse",
    medical: "medical-bag", education: "school", gifts: "gift", gift: "gift",
    housing: "home", rent: "home", salary: "wallet", income: "cash",
};

export function getExpenseCategoryIcon(icon: unknown, name: string): ExpenseCategoryIcon {
    if (typeof icon === "string" && ICON_KEYS.has(icon)) {
        return icon as ExpenseCategoryIcon;
    }
    return DEFAULT_ICONS[name.trim().toLowerCase()] ?? "tag-outline";
}
